[tool.black]
line-length = 120
experimental-string-processing = true

[tool.isort]
profile = "black"
known_local_folder = "sp"
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]

[tool.pylint.master]
# Allow loading of arbitrary C extensions. Extensions are imported into the
# active Python interpreter and may run arbitrary code.
unsafe-load-any-extension='yes'

[tool.pylint.messages_control]
disable = [
    "import-error",
	"missing-module-docstring", "missing-class-docstring", "missing-function-docstring",
	"too-many-public-methods", "too-few-public-methods",
	"import-outside-toplevel",
	"no-member", "no-name-in-module",
	"fixme",
	"invalid-name"
]

[tool.pylint.basic]
good-names = [
	"i", "j", "k", "v", "x", "y",
	"df",
	"ax"
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.design]
max-args = 10
max-attributes = 15
max-locals = 20

[tool.pylint.refactoring]
max-nested-blocks = 3
max-branches = 20

[tool.pylint.similarities]
ignore-imports="yes"

[tool.mypy]
show_column_numbers = true
ignore_missing_imports = true
allow_redefinition = true

[tool.pytest.ini_options]
testpaths = ["test"]
filterwarnings = ["error"]
